/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { GetAccountSummary } from "./domain/usages/get-account-sumary";
import { AccountTransaction } from "./domain/models/account-transaction";
import { GetAccountTransactionList } from "./domain/usages/get-account-transaction-list";
export namespace Components {
    interface AccountSummaryComponent {
        /**
          * Get account summary
         */
        "getAccountSummary": GetAccountSummary;
    }
    interface AccountSummaryComponentFactory {
    }
    interface AccountTransactionComponent {
        /**
          * Account transction
         */
        "transaction": AccountTransaction;
    }
    interface AccountTransactionListComponent {
        /**
          * Get account transaction list
         */
        "getAccountTransactionList": GetAccountTransactionList;
    }
    interface AccountTransactionListComponentFactory {
    }
    interface WalletComponent {
    }
}
declare global {
    interface HTMLAccountSummaryComponentElement extends Components.AccountSummaryComponent, HTMLStencilElement {
    }
    var HTMLAccountSummaryComponentElement: {
        prototype: HTMLAccountSummaryComponentElement;
        new (): HTMLAccountSummaryComponentElement;
    };
    interface HTMLAccountSummaryComponentFactoryElement extends Components.AccountSummaryComponentFactory, HTMLStencilElement {
    }
    var HTMLAccountSummaryComponentFactoryElement: {
        prototype: HTMLAccountSummaryComponentFactoryElement;
        new (): HTMLAccountSummaryComponentFactoryElement;
    };
    interface HTMLAccountTransactionComponentElement extends Components.AccountTransactionComponent, HTMLStencilElement {
    }
    var HTMLAccountTransactionComponentElement: {
        prototype: HTMLAccountTransactionComponentElement;
        new (): HTMLAccountTransactionComponentElement;
    };
    interface HTMLAccountTransactionListComponentElement extends Components.AccountTransactionListComponent, HTMLStencilElement {
    }
    var HTMLAccountTransactionListComponentElement: {
        prototype: HTMLAccountTransactionListComponentElement;
        new (): HTMLAccountTransactionListComponentElement;
    };
    interface HTMLAccountTransactionListComponentFactoryElement extends Components.AccountTransactionListComponentFactory, HTMLStencilElement {
    }
    var HTMLAccountTransactionListComponentFactoryElement: {
        prototype: HTMLAccountTransactionListComponentFactoryElement;
        new (): HTMLAccountTransactionListComponentFactoryElement;
    };
    interface HTMLWalletComponentElement extends Components.WalletComponent, HTMLStencilElement {
    }
    var HTMLWalletComponentElement: {
        prototype: HTMLWalletComponentElement;
        new (): HTMLWalletComponentElement;
    };
    interface HTMLElementTagNameMap {
        "account-summary-component": HTMLAccountSummaryComponentElement;
        "account-summary-component-factory": HTMLAccountSummaryComponentFactoryElement;
        "account-transaction-component": HTMLAccountTransactionComponentElement;
        "account-transaction-list-component": HTMLAccountTransactionListComponentElement;
        "account-transaction-list-component-factory": HTMLAccountTransactionListComponentFactoryElement;
        "wallet-component": HTMLWalletComponentElement;
    }
}
declare namespace LocalJSX {
    interface AccountSummaryComponent {
        /**
          * Get account summary
         */
        "getAccountSummary"?: GetAccountSummary;
    }
    interface AccountSummaryComponentFactory {
    }
    interface AccountTransactionComponent {
        /**
          * Account transction
         */
        "transaction"?: AccountTransaction;
    }
    interface AccountTransactionListComponent {
        /**
          * Get account transaction list
         */
        "getAccountTransactionList"?: GetAccountTransactionList;
    }
    interface AccountTransactionListComponentFactory {
    }
    interface WalletComponent {
    }
    interface IntrinsicElements {
        "account-summary-component": AccountSummaryComponent;
        "account-summary-component-factory": AccountSummaryComponentFactory;
        "account-transaction-component": AccountTransactionComponent;
        "account-transaction-list-component": AccountTransactionListComponent;
        "account-transaction-list-component-factory": AccountTransactionListComponentFactory;
        "wallet-component": WalletComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "account-summary-component": LocalJSX.AccountSummaryComponent & JSXBase.HTMLAttributes<HTMLAccountSummaryComponentElement>;
            "account-summary-component-factory": LocalJSX.AccountSummaryComponentFactory & JSXBase.HTMLAttributes<HTMLAccountSummaryComponentFactoryElement>;
            "account-transaction-component": LocalJSX.AccountTransactionComponent & JSXBase.HTMLAttributes<HTMLAccountTransactionComponentElement>;
            "account-transaction-list-component": LocalJSX.AccountTransactionListComponent & JSXBase.HTMLAttributes<HTMLAccountTransactionListComponentElement>;
            "account-transaction-list-component-factory": LocalJSX.AccountTransactionListComponentFactory & JSXBase.HTMLAttributes<HTMLAccountTransactionListComponentFactoryElement>;
            "wallet-component": LocalJSX.WalletComponent & JSXBase.HTMLAttributes<HTMLWalletComponentElement>;
        }
    }
}
